[workspace]

members = ["bins/evm", "crates/primitives"]

[workspace.dependencies]
alloy = "1.0.41"

# using github
# alloy = {git = "https://github.com/TheOphige/alloy", branch = "main", features = ["compile", "hum"]}